### ISSUE TITLE
DEPENDENCY MANAGEMENT HELP

### ISSUE THREAD

**Issue by jayendramadaram** [NGIT-Open-Source/discord-bot#19]
![image](https://user-images.githubusercontent.com/75383012/131689618-596bb2b0-125b-4ffb-988d-7d3f5a48d4d2.png)

npm ci doesn't work following error occured

**Comment by prithvi2k2** [comment]
What is the version of node when you performed `npm ci`. Ensure it's ^16.6.0 for this project as mentioned in [Step 5 Setup](https://github.com/NGIT-Open-Source/discord-bot/blob/develop/docs/CONTRIBUTIONS.md#step-5-setting-up-your-local-environment) in CONTRIBUTIONS.md
